import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
// import styles from '../styles/Home.module.css'
import profilePic from '../../public/pug-icon-0.png'

const pugs = [
  {
    label: 'Academia Pug',
    src: '/academia-pug.jpg',
    path: 'academia-pug',
    alt: 'A very smart pug'
  },
  {
    label: 'Biker Pug',
    src: '/biker-pug.jpg',
    path: 'biker-pug',
    alt: 'A very tough pug'
  },
  {
    label: 'Buddy Pug',
    src: '/buddy-pug.jpg',
    path: 'buddy-pug',
    alt: 'A very kind pug'
  },
  {
    label: 'Side Glance Pug',
    src: '/side-glance-pug.jpg',
    path: 'side-glance-pug',
    alt: 'A very photogenic pug'
  }
]

export default function ImageGallery() {
  return (
    <div>
      <Head>
        <title>Image Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div class="header" style={{  width: "100%", display:"flex", border: "dashed 2px bisque", backgroundColor:"salmon", overflow: "hidden", padding: "20px 10px"}}>
        <a href="#default" class="logo" style={{  float: "left", color: "black", textAlign: "center", padding: "12px", textDecoration: "none", fontSize: "18px", lineHeight: "25px", borderRadius: "4px"}}>
        <Image src={profilePic} alt="Picture of the author" />
        </a>
        <div class="header-right" style={{margin:"10px"}}>
          <a class="active" href="#home" style={{margin:"10px"}}>Home</a>
          <a href="#contact" style={{margin:"10px"}}>Contact</a>
          <a href="#about" style={{margin:"10px"}}>About</a>
          <a href="#about" style={{margin:"10px"}}>About</a>
          <Link href="/image-gallery"><a style={{ margin: '10px'}}>Image Gallery</a></Link>
        </div>
      </div>

      <main>
        <h1>Image Gallery</h1>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)' }}>
          {pugs.map(({ label, src, alt, path }) => (
            <div key={label} style={{ margin: '0 0 1rem' }}>
              <Link href={`image-gallery/${path}`}>
                <div style={{ width: 300, height: 300, position: 'relative' }}>
                  <Image src={src} alt={alt} layout="fill" objectFit="cover" />
                </div>
              </Link>
              <caption>{label}</caption>
            </div>
          ))}
        </div>
      </main>
    </div>
  )
}
