import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
// import styles from '../styles/Home.module.css'
import profilePic from '../../public/pug-icon-0.png'
import Header from '../components/Header'

const pugs = [
  {
    label: 'Academia Pug',
    src: '/academia-pug.jpg',
    path: 'academia-pug',
    alt: 'A very smart pug'
  },
  {
    label: 'Biker Pug',
    src: '/biker-pug.jpg',
    path: 'biker-pug',
    alt: 'A very tough pug'
  },
  {
    label: 'Buddy Pug',
    src: '/buddy-pug.jpg',
    path: 'buddy-pug',
    alt: 'A very kind pug'
  },
  {
    label: 'Side Glance Pug',
    src: '/side-glance-pug.jpg',
    path: 'side-glance-pug',
    alt: 'A very photogenic pug'
  }
]

export default function ImageGallery() {
  return (
    <div>
      <Head>
        <title>Image Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <h1>Image Gallery</h1>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '1rem' }}>
          {pugs.map(({ label, src, alt, path }) => (
            <div key={label} style={{ margin: '0 0 1rem' }}>
              <Link href={`image-gallery/${path}`}>
                <div style={{ width: '100%', height: 300, position: 'relative', cursor: "pointer" }}>
                  <Image src={src} alt={alt} layout="fill" objectFit="cover" />
                </div>
              </Link>
              <caption style={{ whiteSpace: "nowrap" }}>{label}</caption>
            </div>
          ))}
        </div>
      </main>
    </div>
  )
}
