import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import profilePic from '../public/pug-icon-0.png'
import pugPic from './../public/pug-doughnut.jpg';
import Link from 'next/link';
import Header from './components/Header';

export default function Home() {
  return (
    <div  style={{ backgroundColor: "salmon" }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <Header />
        <h1 className={styles.title}>
          Welcome to <strong>PugFlex</strong>!
        </h1>

        <h2>A Fan Site about Pugs</h2>
        <h3 style={{ fontSize: "24px" }}>PUGS</h3>


        <Image style={{ border: '3px dotted bisque' }} src={pugPic} alt="pug" width={500}
          height={500} />

        <h3>Learn More About Pugs</h3>
        <p>This is a pug fan site -- learn all about pugs</p>
      </main>

      <footer className={styles.footer} styles={{ border: "none" }}>

      </footer>
    </div>
  )
}
