import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import pugPic from './../public/pug-doughnut.jpg';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <strong>PugFlex</strong>!
        </h1>

        <Image src={pugPic} alt="pug" width={500}
          height={500} />

      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
