import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import profilePic from '../../public/pug-icon-0.png'
import Header from '../components/Header'

export default function ImageGallery() {
  return (
    <div>
      <Head>
        <title>Image Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
      <h1>Anatomy</h1>
        <ul>
          <li>Characterized by their wrinkly face</li>
          <li>Curled tail</li>
          <li>Square muscular body with large head, big eyes and small ears</li>
          <li>Coat colors </li>
        </ul>
      </main>
    </div>
  )
}
